services:

  # =========================================================
  # KAFKA
  # =========================================================
  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka

    ports:
      - "9092:9092"

    environment:
      # KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # Listeners
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

      # Client addresses
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092

      # Security mapping
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      # Broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # KRaft controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Single-node Kafka
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Local development
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    networks:
      - app-network


  # =========================================================
  # MYSQL
  # =========================================================
  mysql:
    image: mysql:8.0
    container_name: mysql

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - app-network


  # =========================================================
  # USER SERVICE
  # =========================================================
  user-service:
    build:
      context: ./user-service

    container_name: user-service

    ports:
      - "8081:8081"

    environment:
      SERVER_PORT: 8081

      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: micro_user_db
      DB_USERNAME: root
      DB_PASSWORD: root

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - app-network


  # =========================================================
  # ORDER SERVICE
  # =========================================================
  order-service:
    build:
      context: ./order-service

    container_name: order-service

    ports:
      - "8082:8082"

    environment:
      SERVER_PORT: 8082

      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: micro_order_db
      DB_USERNAME: root
      DB_PASSWORD: root

      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

      USER_SERVICE_URL: http://user-service:8081

    depends_on:
      mysql:
        condition: service_healthy

      kafka:
        condition: service_started

      user-service:
        condition: service_started

    networks:
      - app-network


  # =========================================================
  # PAYMENT SERVICE
  # =========================================================
  payment-service:
    build:
      context: ./payment-service

    container_name: payment-service

    ports:
      - "8083:8083"

    environment:
      SERVER_PORT: 8083

      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: micro_payment_db
      DB_USERNAME: root
      DB_PASSWORD: root

      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

      KAFKA_CONSUMER_GROUP: payment-service

    depends_on:
      mysql:
        condition: service_healthy

      kafka:
        condition: service_started

    networks:
      - app-network


# =========================================================
# VOLUMES
# =========================================================
volumes:
  mysql-data:


# =========================================================
# NETWORK
# =========================================================
networks:
  app-network:
    driver: bridge